### PR TITLE
sale_channel_search_engine: add module

### PR DESCRIPTION
**Pull request by sebastienbeau**
Add sale_channel_search_engine
TODO :
- [x] implement the feature
- [x] improve UI

### CODE REVIEW

**Comment by sebastienbeau** [comment]
I will work on the UI this end of week

**Review by hparfr — APPROVED** [review]

**Comment by qgroulard** [comment]
Here we should also call `_se_mark_to_update()` when product and categories are modifier right ?

**Comment by hparfr** [comment]
- [x] https://github.com/akretion/sale-channel/pull/1
- [x] https://github.com/akretion/sale-channel/pull/2

**Pull request merged**
