### PR TITLE
[16.0] sale_channel_crm: add module

### PR DESCRIPTION
**Pull request by pepetreshere**

### CODE REVIEW

**Comment by gatunosh** [comment]
@rvalyi

**Comment by gatunosh** [comment]
@azmeuk please could you help us merge this pull request?

**Comment by gatunosh** [comment]
@rvalyi could u help us merge this pull request please?

**Comment by pepetreshere** [comment]
@sebastienbeau maybe you could help us review this PR for merge? (not really sure to who to direct this request, I see you have made other contributions in this same repo)

**Comment by gatunosh** [comment]
@rvalyi maybe could you please help us merge this PR? I have seend you made some contributions in this repo as well.

**Review by rvalyi — APPROVED** [review]
LGTM

**Comment by gatunosh** [comment]
Hi! @rvalyi thanks for approving the code however in the checks there is still one pending "runboat/build". I have not been able to see the "details" to check the instance, maybe that instance can only be checked by you and you approve it yourself? Or we have to generate something else to finish the merge process?

Thanks in advace!

**Comment by rvalyi** [comment]
Hello @gatunosh
Problems with the Runboat do happen in the  OCA... It's not blocking but if you want to trigger it again you might do a git push -f in the branch. 

What is missing at this stage is another approval from some important reviewer... 
cc @OCA/crm-sales-marketing-maintainers

**Pull request closed without merging**
